replicaCount: 2

image:
  repository: prajwalbambulkar/3tiernodejs
  tag: frontend-29          # <-- Update manually to deploy new frontend build
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

containerPort: 80
