replicaCount: 2

image:
  repository: prajwalbambulkar/3tiernodejs
  tag: frontend-22          # <-- Update manually to deploy new frontend build
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

containerPort: 8080
