replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

image:
  repository: prajwalbambulkar/frontend
  tag: frontend-24
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 80
color: blue
activeColor: blue

ingress:
  enabled: true
  className: nginx
  host: frontend.local

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
