apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-container
  labels:
    app: mysql-container
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mysql-container
  template:
    metadata:
      labels:
        app: mysql-container
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mysqlRootPassword }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.mysqlDatabase }}"
          ports:
            - containerPort: 3306
              name: mysql
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        {{- end }}

