apiVersion: v1
kind: Service
metadata:
  name: mysql-container
  labels:
    app: mysql-container
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app: mysql-container

