apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-{{ .Values.color }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
      color: {{ .Values.color }}
  template:
    metadata:
      labels:
        app: frontend
        color: {{ .Values.color }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
