apiVersion: v1
kind: Service
metadata:
  name: frontend-{{ .Values.color }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend
    color: {{ .Values.color }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
