apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          ports:
            - containerPort: {{ .Values.containerPort }}

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

          env:
            - name: DB_HOST
              value: "{{ .Values.env.DB_HOST }}"

            - name: DB_USER
              value: "{{ .Values.env.DB_USER }}"

            - name: DB_PASS
              value: "{{ .Values.env.DB_PASS }}"

            - name: DB_NAME
              value: "{{ .Values.env.DB_NAME }}"

            - name: DB_PORT
              value: "{{ .Values.env.DB_PORT }}"

          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            periodSeconds: 5
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
